# Generated by Django 4.2.19 on 2025-02-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(help_text='用户ID', primary_key=True, serialize=False)),
                ('username', models.CharField(help_text='用户名', max_length=50, unique=True)),
                ('password', models.CharField(help_text='密码', max_length=128)),
                ('nick_name', models.CharField(blank=True, help_text='昵称', max_length=50, null=True)),
                ('description', models.TextField(blank=True, help_text='描述', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'user',
            },
        ),
    ]
