# Generated by Django 4.2.19 on 2025-02-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False, verbose_name='账户ID')),
                ('account_type', models.CharField(choices=[('CASH', '现金'), ('BANK', '银行卡'), ('ALIPAY', '支付宝'), ('WECHAT', '微信'), ('HOUSING_FUND', '公积金')], max_length=20, verbose_name='账户类型')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='账户余额')),
                ('account_name', models.CharField(max_length=100, verbose_name='账户名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '账户',
                'verbose_name_plural': '账户',
                'db_table': 'account',
            },
        ),
    ]
